// <auto-generated />
using System;
using Api_Arancia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Arancia.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20231213190109_Projetos e Empresa")]
    partial class ProjetoseEmpresa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api_Arancia.Modelos.Desenvolvedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Desenvolvedores");
                });

            modelBuilder.Entity("Api_Arancia.Modelos.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Api_Arancia.Modelos.Projetos", b =>
                {
                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int?>("DesenvolvedoresId")
                        .HasColumnType("int");

                    b.HasKey("EmpresaId", "DesenvolvedoresId");

                    b.HasIndex("DesenvolvedoresId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("Api_Arancia.Modelos.Projetos", b =>
                {
                    b.HasOne("Api_Arancia.Modelos.Desenvolvedores", "Desenvolvedores")
                        .WithMany("Projetos")
                        .HasForeignKey("DesenvolvedoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_Arancia.Modelos.Empresa", "Empresa")
                        .WithMany("Projetos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desenvolvedores");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Api_Arancia.Modelos.Desenvolvedores", b =>
                {
                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("Api_Arancia.Modelos.Empresa", b =>
                {
                    b.Navigation("Projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
